### ISSUE TITLE
Debian of other ditros icons

### ISSUE THREAD

**Issue by moniika21** [x70b1/motd-on-acid#2]
Hello, where can i find debian or other icons on the web to put it in the file ?
Does the file accept .img or .ico ?
I've searched in [Debian logos](https://www.debian.org/logos/) but I don't know what to take and put to look like your cute little icon on your preview.
Thanks in advance !

**Comment by x70b1** [comment]
As [described](https://github.com/x70b1/motd-on-acid#preview), I used an icon font (Font Awesome) and fontello to create my own icon font. You can upload SVG files there. It will generate an icon in a font for you.

You could try this: [debian.org/logos/openlogo-nd.svg](https://www.debian.org/logos/openlogo-nd.svg)

**Comment by moniika21** [comment]
Ah yeah didn't read this part, thanks !
