### ISSUE TITLE
Question about icons

### ISSUE THREAD

**Issue by rvalitov** [x70b1/motd-on-acid#4]
Hi! A great script! Can you please give more info how to use icons? I need to get some font then inject the required icons inside and after that put this font as a system terminal font? How to achieve the last step? I use Debian.

**Comment by x70b1** [comment]
Yes, you have to use an icon font. There are multiple fonts possible: `nerd-fonts`, `font-awesome` ... 
Install that font and set them in the predefined vars. 

A helpful tool is also `gucharmap`.

**Comment by rvalitov** [comment]
Thank you for a prompt response! I saved/installed the font in Debian as explained in the [docs](https://wiki.debian.org/Fonts#Manually), and I see that that the system now sees the new font, but I don't understand how to set this font to be used in your script or in SSH session. Can you please let me know how can I achieve that?

**Comment by x70b1** [comment]
Its written here: [Setup](https://github.com/x70b1/motd-on-acid?tab=readme-ov-file#setup)

X, Y, Z are the "Icons" that you have to replace.

**Comment by rvalitov** [comment]
Ok, I put a character code instead of X,Y,Z that corresponds to the icon in the new font, for example, it's Font Awesome. Correct? But how to specify that this character code is from Font Awesome and not from font Helvetica or any other font that I have installed/available on the server?

**Comment by x70b1** [comment]
Thats something your system will resolve for you. Icon fonts use "characters" which are not used typically. So it knows thats the only possible font icon there.

The icon font needs to be installed on your local system.

**Comment by rvalitov** [comment]
Thank you, I could figure it out. Below are my comments for those who would issue similar questions:
- the font should be installed locally on the machine that you connect from, not on the remote server
- you should put the character itself (not the character code) instead of X, Y, Z. I tried to use the character codes in HEX and decimal format - that did not work
- automatic font submission did not work, i.e. I had to create a new font that will merge the standard text characters from the default font such as Courier, Times, etc. with icons from the icon font (Font Awesome, etc.). And then this font should be configured to be used on the local machine in the SSH client.
